title: Piaoyang Cui
email: piaoyangcui@gmail.com
description: Software Engineer, Entrepreneur<br><br>👉 Read <a href="https://piaoyang0.wordpress.com">My blog</a><br><br>🏠 Visit <a href="https://homeproject.fyi">homeproject.fyi</a>, my home project data collection site.
baseurl: "" # the subpath of your site, e.g., /blog if your site is hosted at example.com/blog
url: "https://piaoyang.me/" # the base hostname & protocol for your site
google_analytics: 'G-YVE89E7ZGS'

# Build settings
theme: jekyll-theme-minimal # or any other theme you have selected through the theme chooser or manually
plugins:
  - jekyll-feed

# Optional settings
twitter_username: yourusername
github_username: yourusername
linkedin_username: yourlinkedin

# SEO tags (optional but recommended for better SEO)
author: Piaoyang Cui
twitter:
  username: pycui64

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Social links (customize these with your own usernames or remove any you don't want to include)
social_links:
  twitter: https://twitter.com/pycui64
  github: https://github.com/pycui
  linkedin: https://linkedin.com/in/piaoyang

# Markdown settings (optional, for more advanced users)
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..6
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
